image_root: 'export/datasets/images/'
ann_root: 'annotation'
cctv_gt_root: 'annotation/coco_gt'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'
# fine-tuned 된 url도 있음!
# 이 문자열을 우리의 fine-tuned된 모델의 경로로 두는 방법 -> if/else 구문으로, else로 빠지면 폴더 경로로 잡아냄.

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 8
# batch_size: 32
init_lr: 1e-5
# init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 70  
min_length: 5
num_beams: 3
prompt: ''

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5

